title: Social Knowledge Network
default_lang: fr

author:
  name: SKN Team
  email: contact@skn.local

metadata:
  description: RÃ©seau social de partage de connaissances

routes:
  '/room/(.*)': '/sys/room'
  '/profile/(.*)': '/sys/profiles/dispatcher'
  '/mesrooms': '/mesrooms'
