absolute_urls: false

# Validation des utilisateurs (regex plus permissifs)
username_regex: '^[a-z0-9_\-\.]{3,32}$'
pwd_regex: '.{8,}'

home:
  alias: '/home'

pages:
  theme: quark
  markdown:
    extra: false
  process:
    markdown: true
    twig: false

cache:
  enabled: false
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: false
  debug: true
  auto_reload: true
  autoescape: true

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_module_pipeline: false
  js_minify: true

errors:
  display: true
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
gpm:
  verify_peer: true

session:
  enabled: true
  initialize: true
  timeout: 1800
  name: skn-session
  uniqueness: path
  secure: false
  httponly: true
  split: true
  path: null
